services:
  db:
    build:
      context: ./prisma
      dockerfile: Dockerfile
    ports:
      - 33306:3306
    environment:
      - MYSQL_DATABASE=crowdr
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql:delegated

volumes:
  db-data:
